TEST_DIR="test_src"

test: build
	passed=0; \
	for filename in ${TEST_DIR}/*.kek; \
	do \
	    ./a.out $${filename} > /dev/null; \
	    if [ $$? -eq 0 ]; \
	        then passed=$$(( $${passed} + 1 )); \
	    fi; \
	done; \
	echo "Tests passed: $${passed} / $$(ls ${TEST_DIR}/*.kek | wc -l)"
